on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      #- name: access
       # run: chmod +x entrypoint.sh
      
      - name: Hello world action step
        uses: ./ #NisargShah1410/gh-docker-demo@v2.1 # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Show WebApp Profile
        shell: bash
        run: |
          echo "WebApp: ${{ steps.hello.outputs.profile }}"
      # Use the output from the `hello` step
      #- name: Get the output time
       # run: echo "The time was ${{ steps.hello.outputs.time }}"
